MVC_Demo/Controllers/MoiveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common.CommandTrees;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Demo.Models;

namespace MVC_Demo.Controllers
{
    public class MoiveController : Controller
    {
        private MoiveDbContext db = new MoiveDbContext();

        //
        // GET: /Moive/

        public ActionResult Index()
        {
            return View(db.Moives.ToList());
        }

        //
        // GET: /Moive/Details/5

        public ActionResult Details(int id = 0)
        {
            Moive moive = db.Moives.Find(id);
            if (moive == null)
            {
                return HttpNotFound();
            }
            return View(moive);
        }

        //
        // GET: /Moive/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Moive/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Moive moive)
        {
            if (ModelState.IsValid)
            {
                db.Moives.Add(moive);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(moive);
        }

        //
        // GET: /Moive/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Moive moive = db.Moives.Find(id);
            if (moive == null)
            {
                return HttpNotFound();
            }
            return View(moive);
        }

        //
        // POST: /Moive/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Moive moive)
        {
            if (ModelState.IsValid)
            {
                db.Entry(moive).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(moive);
        }

        //
        // GET: /Moive/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Moive moive = db.Moives.Find(id);
            if (moive == null)
            {
                return HttpNotFound();
            }
            return View(moive);
        }

        //
        // POST: /Moive/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Moive moive = db.Moives.Find(id);
            db.Moives.Remove(moive);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult SearchIndex(string moiveGeren,string SearchString)
        {
            var geren = new List<string>();
            var querygeren = from p in db.Moives
                orderby p.Genre
                select p.Genre;
            geren.AddRange(querygeren.Distinct());

            ViewBag.moiveGeren = new SelectList(geren);

            var moives = from m in db.Moives
                select m;
            if (!string.IsNullOrEmpty(SearchString))
            {
                moives = moives.Where(c => c.Title.Contains(SearchString));
            }
            if (string.IsNullOrEmpty(moiveGeren))
                return View(moives);
            return View(moives.Where(c => c.Genre == moiveGeren));
            
        }
    }
}

MVC_Demo/Views/Moive/Create.cshtml
@model MVC_Demo.Models.Moive

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Moive</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseTime)
            @Html.ValidationMessageFor(model => model.ReleaseTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Genre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Genre)
            @Html.ValidationMessageFor(model => model.Genre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Demo/Views/Moive/Delete.cshtml
@model MVC_Demo.Models.Moive

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Moive</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Genre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Genre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MVC_Demo/Views/Moive/Details.cshtml
@model MVC_Demo.Models.Moive

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Moive</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ReleaseTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ReleaseTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Genre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Genre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC_Demo/Views/Moive/Edit.cshtml
@model MVC_Demo.Models.Moive

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Moive</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ReleaseTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ReleaseTime)
            @Html.ValidationMessageFor(model => model.ReleaseTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Genre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Genre)
            @Html.ValidationMessageFor(model => model.Genre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC_Demo/Views/Moive/Index.cshtml
@model IEnumerable<MVC_Demo.Models.Moive>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

MVC_Demo/Views/Moive/SearchIndex.cshtml
@model IEnumerable<MVC_Demo.Models.Moive>

@{
    ViewBag.Title = "SearchIndex";
}

<h2>SearchIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")


    @using (Html.BeginForm("SearchIndex","Moive",FormMethod.Get))
    {
        <p>
            Genre: @Html.DropDownList("moiveGeren", "All")
            Title: @Html.TextBox("SearchString")<br />
            <input type="submit" value="筛选" />
        </p>
    }
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                </td>
            </tr>
        }

    </table>